# Generated by Django 5.2.13 on 2026-09-12 03:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityTestCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text="Slug identifier, e.g. 'food', 'free_time', 'infrastructure'", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable category name.', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'City Test Category',
                'verbose_name_plural': 'City Test Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SoloMicroTestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Solo Micro-Test Group',
                'verbose_name_plural': 'Solo Micro-Test Groups',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CityTest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.SlugField(help_text="Slug identifier, e.g. 'everyday-lunch'", max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, default='')),
                ('google_maps_link', models.URLField(blank=True, default='')),
                ('external_links', models.JSONField(blank=True, default=list, help_text='Array of {"label": str, "url": str} objects.')),
                ('note_prompts', models.JSONField(blank=True, default=list, help_text='Array of prompt strings shown to guide user notes.')),
                ('question_prompts', models.JSONField(blank=True, default=list, help_text='Array of question strings the client should answer for the Liv team.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the category.')),
                ('category', models.ForeignKey(help_text='The category this test belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='livable.citytestcategory')),
            ],
            options={
                'verbose_name': 'City Test',
                'verbose_name_plural': 'City Tests',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='The date of this schedule (YYYY-MM-DD).')),
                ('client', models.ForeignKey(help_text='The client this schedule belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='clients.client')),
            ],
            options={
                'verbose_name': 'Daily Schedule',
                'verbose_name_plural': 'Daily Schedules',
                'ordering': ['date'],
                'unique_together': {('client', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — safe to expose in API responses.', primary_key=True, serialize=False)),
                ('start_time', models.CharField(help_text='Start time in HH:MM format, e.g. 09:00', max_length=5)),
                ('end_time', models.CharField(help_text='End time in HH:MM format, e.g. 11:00', max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('meeting', 'Meeting'), ('recommendation', 'Recommendation'), ('open_time', 'Open Time'), ('hotel', 'Hotel')], default='meeting', help_text='Type of schedule item.', max_length=20)),
                ('short_description', models.CharField(blank=True, default='', help_text='Brief summary shown in the collapsed list view.', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('host_name', models.CharField(blank=True, default='', max_length=255)),
                ('meeting_point', models.CharField(blank=True, default='', max_length=500)),
                ('what_to_bring', models.CharField(blank=True, default='', max_length=500)),
                ('google_maps_link', models.URLField(blank=True, default='')),
                ('restaurant_link', models.URLField(blank=True, default=None, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('website', models.URLField(blank=True, default=None, null=True)),
                ('reminder', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Controls display order within the day.')),
                ('schedule', models.ForeignKey(help_text='The daily schedule this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='livable.dailyschedule')),
            ],
            options={
                'verbose_name': 'Schedule Item',
                'verbose_name_plural': 'Schedule Items',
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SoloMicroTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='livable.solomicrotestgroup')),
            ],
            options={
                'verbose_name': 'Solo Micro-Test',
                'verbose_name_plural': 'Solo Micro-Tests',
                'ordering': ['group__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CityTestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('question_for_liv_team', models.TextField(blank=True, default='')),
                ('links', models.JSONField(blank=True, default=list, help_text='Array of URL strings the client wants to save.')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_test_submissions', to='clients.client')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='livable.citytest')),
            ],
            options={
                'verbose_name': 'City Test Submission',
                'verbose_name_plural': 'City Test Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('client', 'test')},
            },
        ),
    ]
