# Generated by Django 6.1.1 on 2026-09-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livable', '0002_citytest_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='end_time',
            field=models.CharField(blank=True, help_text='End time in HH:MM format, e.g. 11:00', max_length=5, null=True),
        ),
    ]
