# Generated by Django 6.1.1 on 2026-09-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livable', '0003_alter_scheduleitem_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytestsubmission',
            name='links',
            field=models.JSONField(blank=True, default=list, help_text='Array of URL strings the client wants to save.', null=True),
        ),
    ]
