# Generated by Django 5.2.13 on 2026-09-12 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('relocation_process_type', models.CharField(choices=[('just_exploring', 'Just starting to explore'), ('researching', 'Researching independently'), ('know_move_not_where', 'I know I want to move, but not where'), ('specific_city', 'I have a specific city in mind'), ('ready_scouting', 'Ready to schedule a scouting trip')], help_text='Where the user is in their relocation journey.', max_length=50)),
                ('considering_places_type', models.CharField(help_text='Comma-separated place choices: lisbon_porto | san_sebastian_malaga | valencia_malaga | not_sure', max_length=255)),
                ('scouting_people_type', models.CharField(choices=[('just_me', 'Just me'), ('two_people', 'Two people')], max_length=20)),
            ],
            options={
                'verbose_name': 'Anonymous Booking',
                'verbose_name_plural': 'Anonymous Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('target_destination', models.CharField(max_length=255)),
                ('visa', models.CharField(max_length=255)),
                ('target_arrival_timeline', models.CharField(default='October 2026 Arrival', help_text='e.g. October 2026 Arrival', max_length=100)),
                ('household_size', models.CharField(max_length=50)),
                ('lead_advisor_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(blank=True, help_text='The portal login user linked to this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivating_factors', models.TextField(blank=True, default='', help_text='Comma-separated motivation keys: lower_costs | more_space | better_quality | financial_flexibility | retirement | remote_work | larger_runway | figuring_out')),
                ('financial_note', models.TextField(blank=True, default='')),
                ('comfortable_housing_budget', models.CharField(blank=True, default='', max_length=100)),
                ('stretched_housing_budget', models.CharField(blank=True, default='', max_length=100)),
                ('monthly_living_budget_target', models.CharField(blank=True, default='', max_length=100)),
                ('financial_expectation', models.CharField(blank=True, choices=[('maintain_lifestyle', 'Maintain my current spending while improving my lifestyle.'), ('reduce_expenses', 'Reduce my monthly expenses while maintaining my current lifestyle.'), ('spend_more_quality', 'Spend a little more to prioritize quality of life.'), ('spend_less_compromise', 'Spend less, even if it means making compromises.'), ('figuring_out', "I'm still figuring that out.")], default='', max_length=50)),
                ('income_route', models.CharField(blank=True, choices=[('remote_employment', 'Remote employment'), ('business_income', 'Business income'), ('retirement_pension', 'Retirement or pension'), ('investment_income', 'Investment income'), ('figuring_out', 'Still figuring it out')], default='', max_length=30)),
                ('income_route_note', models.TextField(blank=True, default='')),
                ('willing_tradeoffs', models.TextField(blank=True, default='', help_text='Comma-separated: housing_size | commute_time | walkability | public_transport | nightlife | climate | distance_city_center | monthly_budget | peace_of_life | other')),
                ('unwilling_tradeoffs_note', models.TextField(blank=True, default='')),
                ('practical_constraints', models.TextField(blank=True, default='', help_text='Comma-separated: buy_home | time_outside | children | pets | accessibility | tax_complexity | budget | other')),
                ('practical_constraints_note', models.TextField(blank=True, default='')),
                ('specific_cost_worries', models.TextField(blank=True, default='')),
                ('financial_excitement_factors', models.TextField(blank=True, default='', help_text='Comma-separated: groceries | local_markets | no_car | public_transport | healthcare | dining | public_spaces | more_budget | other')),
                ('financial_excitement_note', models.TextField(blank=True, default='')),
                ('client', models.OneToOneField(help_text='One financial profile per client.', on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to='clients.client')),
            ],
            options={
                'verbose_name': 'Financial Profile',
                'verbose_name_plural': 'Financial Profiles',
            },
        ),
        migrations.CreateModel(
            name='LifestyleAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_life_desires', models.TextField(blank=True, default='', help_text='Comma-separated: walking | outdoors | water_beaches | cafes | local_markets | language_learning | fitness | arts_culture | green_nature | slower_mornings | lively_evenings | community | deep_family | family_friendly | quiet | beauty | ease | other')),
                ('good_weekday', models.TextField(blank=True, default='')),
                ('good_weekend', models.TextField(blank=True, default='')),
                ('routines_note', models.TextField(blank=True, default='')),
                ('current_day_description', models.TextField(blank=True, default='')),
                ('environmental_pull_factors', models.TextField(blank=True, default='', help_text='Comma-separated: outdoors | different_culture | slower_pace | beautiful_environment | natural_light | coast_access | explore_europe | outside_comfort_zone | comfortably_familiar | feels_like_me | other')),
                ('environmental_pull_note', models.TextField(blank=True, default='')),
                ('internal_pull_factors', models.TextField(blank=True, default='', help_text='Comma-separated: brave | exciting | scary_good | calm | ready_change | always_meant | right_time | chance_grow | fresh_start | figuring_out | other')),
                ('internal_pull_note', models.TextField(blank=True, default='')),
                ('shadow_fear', models.TextField(blank=True, default='', help_text='The Shadow: What they are most afraid of / worried they might regret.')),
                ('anchor_aspiration', models.TextField(blank=True, default='', help_text='The Anchor: The secret, specific thing their future European self will get.')),
                ('success_picture', models.TextField(blank=True, default='')),
                ('desired_emotions', models.TextField(blank=True, default='')),
                ('glad_i_did_this_moment', models.TextField(blank=True, default='')),
                ('client', models.OneToOneField(help_text='One lifestyle profile per client.', on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_alignment', to='clients.client')),
            ],
            options={
                'verbose_name': 'Lifestyle Alignment',
                'verbose_name_plural': 'Lifestyle Alignments',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=255)),
                ('timeline', models.CharField(help_text='Human-readable date range, e.g. Nov 12 - Nov 15, 2026', max_length=100)),
                ('guide_name', models.CharField(help_text='Guide name — pathoprodorshok er naam', max_length=255)),
                ('property_views', models.PositiveIntegerField(default=0, help_text='Number of properties planned to view during this trip.')),
                ('client', models.ForeignKey(help_text='The client this trip belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='clients.client')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
