# Generated by Django 6.1.1 on 2026-09-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='general_monthly_living_budget_target',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='share_your_opinion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='specific_codes_worried_about',
            field=models.TextField(blank=True, default=''),
        ),
    ]
