# Generated by Django 6.1.1 on 2026-09-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_financialprofile_general_monthly_living_budget_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestylealignment',
            name='anything_to_add',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lifestylealignment',
            name='day_looked_like',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lifestylealignment',
            name='emotions_hope_to_feel',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lifestylealignment',
            name='imagine_life_working',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lifestylealignment',
            name='routines_real_life',
            field=models.TextField(blank=True, default=''),
        ),
    ]
